# Generated by Django 4.1.5 on 2023-01-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='get_grants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentgetgrants'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentstatus'),
        ),
    ]
