# Generated by Django 4.1.5 on 2023-01-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_departments_department_rename_groups_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
            preserve_default=False,
        ),
    ]
