# Generated by Django 4.1.5 on 2023-01-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mark_value_alter_student_get_grants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.PositiveIntegerField(default=57),
        ),
    ]
